const products = {
  mobiles: [
    {
      id: 1,
      img: "https://images.olx.com.pk/thumbnails/566596844-400x300.webp",
      price: "Rs 70,000",
      title: "Samsung Galaxy S21 8/128 PTA Approved",
      time: "1 week ago",
      description: "Ye mobile 100% original PTA approved hai.",
      location: "Lahore",
    },
    {
      id: 2,
      img: "https://images.olx.com.pk/thumbnails/567430484-400x300.webp",
      price: "Rs 2.50 Lac",
      title: "Samsung Galaxy S25 – 512GB Warranty Available",
      time: "2 weeks ago",
      description: "Latest Samsung flagship with 512GB storage.",
      location: "Karachi",
    },
    {
      id: 3,
      img: "https://images.olx.com.pk/thumbnails/566596844-400x300.webp",
      price: "Rs 70,000",
      title: "Samsung Galaxy S21 8/128 PTA Approved",
      time: "1 week ago",
      description: "Ye mobile 100% original PTA approved hai.",
      location: "Lahore",
    },
    {
      id: 4,
      img: "https://images.olx.com.pk/thumbnails/567430484-400x300.webp",
      price: "Rs 2.50 Lac",
      title: "Samsung Galaxy S25 – 512GB Warranty Available",
      time: "2 weeks ago",
      description: "Latest Samsung flagship with 512GB storage.",
      location: "Karachi",
    },
  ],
  vehicles: [
    {
      id: 5,
      img: "https://images.olx.com.pk/thumbnails/566240047-400x300.webp",
      price: "Rs 8,50,000",
      title: "Toyota Corolla Xli",
      time: "4 days ago",
      description: "Family car in excellent condition.",
      location: "Islamabad",
    },
    {
      id: 6,
      img: "https://images.olx.com.pk/thumbnails/566240047-400x300.webp",
      price: "Rs 8,50,000",
      title: "Toyota Corolla Xli",
      time: "4 days ago",
      description: "Family car in excellent condition.",
      location: "Islamabad",
    },
    {
      id: 7,
      img: "https://images.olx.com.pk/thumbnails/566240047-400x300.webp",
      price: "Rs 8,50,000",
      title: "Toyota Corolla Xli",
      time: "4 days ago",
      description: "Family car in excellent condition.",
      location: "Islamabad",
    },
    {
      id: 8,
      img: "https://images.olx.com.pk/thumbnails/566240047-400x300.webp",
      price: "Rs 8,50,000",
      title: "Toyota Corolla Xli",
      time: "4 days ago",
      description: "Family car in excellent condition.",
      location: "Islamabad",
    },
  ],
  property: [
    {
      id: 9,
      img: "https://images.olx.com.pk/thumbnails/567501498-400x300.webp",
      price: "Rs 8,50,000",
      title: "Toyota Corolla Xli",
      time: "4 days ago",
      description: "Family car in excellent condition.",
      location: "Islamabad",
    },
    {
      id: 10,
      img: "https://images.olx.com.pk/thumbnails/562190774-400x300.webp",
      price: "Rs 8,50,000",
      title: "Toyota Corolla Xli",
      time: "4 days ago",
      description: "Family car in excellent condition.",
      location: "Islamabad",
    },
    {
      id: 11,
      img: "https://images.olx.com.pk/thumbnails/568399500-400x300.webp",
      price: "Rs 8,50,000",
      title: "Toyota Corolla Xli",
      time: "4 days ago",
      description: "Family car in excellent condition.",
      location: "Islamabad",
    },
    {
      id: 12,
      img: "https://images.olx.com.pk/thumbnails/569429994-400x300.webp",
      price: "Rs 8,50,000",
      title: "Toyota Corolla Xli",
      time: "4 days ago",
      description: "Family car in excellent condition.",
      location: "Islamabad",
    },
  ],
  rent: [
    {
      id: 13,
      img: "https://images.olx.com.pk/thumbnails/565551502-400x300.webp",
      price: "Rs 8,50,000",
      title: "Toyota Corolla Xli",
      time: "4 days ago",
      description: "Family car in excellent condition.",
      location: "Islamabad",
    },
    {
      id: 14,
      img: "https://images.olx.com.pk/thumbnails/565656486-400x300.webp",
      price: "Rs 8,50,000",
      title: "Toyota Corolla Xli",
      time: "4 days ago",
      description: "Family car in excellent condition.",
      location: "Islamabad",
    },
    {
      id: 15,
      img: "https://images.olx.com.pk/thumbnails/560762099-400x300.webp",
      price: "Rs 8,50,000",
      title: "Toyota Corolla Xli",
      time: "4 days ago",
      description: "Family car in excellent condition.",
      location: "Islamabad",
    },
    {
      id: 16,
      img: "https://images.olx.com.pk/thumbnails/569383999-400x300.webp",
      price: "Rs 8,50,000",
      title: "Toyota Corolla Xli",
      time: "4 days ago",
      description: "Family car in excellent condition.",
      location: "Islamabad",
    },
  ],
};

export default products;
